services:
  mini-linkwarden:
    image: ghcr.io/opaleiei/linkwardendial:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mini-linkwarden
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    environment:
      - PORT=3000
      - API_TOKEN=mysecrettoken
